name: Ingestao diaria de dados sismicos

on:
  schedule:
    - cron: "17 6 * * *"
  workflow_dispatch:

jobs:
  ingestao:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o codigo do repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Rodar ingest.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python src/ingest.py